# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.TextField()),
                ('document', models.FileField(upload_to='documents/')),
                ('hall_status', models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active')),
            ],
            options={
                'db_table': 'e_hall',
            },
        ),
    ]
