# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0003_auto_20180728_0016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ehall',
            table='s_hall',
        ),
    ]
