# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0005_auto_20180728_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehall',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createblackforest_ehall_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ehall',
            name='updatedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateblackforest_ehall_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
