# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0006_auto_20180728_0031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ehall',
            table='study_hall',
        ),
    ]
