# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0007_auto_20180728_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehall',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ehall',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='ehall',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='ehall',
            name='updatedby',
        ),
    ]
