# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0008_auto_20180728_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ehall',
            new_name='Shall',
        ),
        migrations.AlterModelTable(
            name='shall',
            table='s_hall',
        ),
    ]
