# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0009_auto_20180728_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shall',
            name='name',
        ),
    ]
