# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0010_remove_shall_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shall',
            table=None,
        ),
    ]
