# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackforest', '0011_auto_20180728_0053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shall',
        ),
    ]
