# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_auto_20180716_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('phone', models.CharField(max_length=13)),
                ('mailid', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('doc_no', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'expense',
            },
        ),
    ]
