# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180801_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eexpenses',
            name='dec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
