# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180801_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ehall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ehall')),
            ],
        ),
    ]
