# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackerlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
