# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trackerlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerlogs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
