# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_studyhall'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhall',
            name='hall_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
    ]
