# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0003_studyhall_hall_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhall',
            name='document_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ice.Document'),
            preserve_default=False,
        ),
    ]
