# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0004_studyhall_document_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyhall',
            old_name='document_no',
            new_name='document',
        ),
    ]
