# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0005_auto_20180728_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyhall',
            old_name='document',
            new_name='doc',
        ),
    ]
