# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0007_auto_20180728_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhall',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyhall_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studyhall_requests_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
