# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0008_auto_20180728_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyhall',
            name='atrribute6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
