# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0010_auto_20180728_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
