# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0011_requesttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracker',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
