# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'e_course',
            },
        ),
        migrations.CreateModel(
            name='Eenquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ecourse')),
            ],
            options={
                'db_table': 'e_enquiry',
            },
        ),
        migrations.CreateModel(
            name='Eexpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('dec', models.TextField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'e_expenses',
            },
        ),
        migrations.CreateModel(
            name='Ehall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('area', models.TextField()),
            ],
            options={
                'db_table': 'e_hall',
            },
        ),
        migrations.CreateModel(
            name='Estudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'e_student',
            },
        ),
        migrations.AddField(
            model_name='eexpenses',
            name='ehall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ehall'),
        ),
        migrations.AddField(
            model_name='eenquiry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Estudent'),
        ),
    ]
