# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecourse',
            name='course_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
        migrations.AddField(
            model_name='eenquiry',
            name='enquiry_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
        migrations.AddField(
            model_name='eexpenses',
            name='exp_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
        migrations.AddField(
            model_name='ehall',
            name='hall_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
        migrations.AddField(
            model_name='estudent',
            name='student_status',
            field=models.IntegerField(default=1, help_text=' 1 - active, 0 - de_active'),
        ),
    ]
