# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='USER FULL NAME')),
                ('username', models.CharField(max_length=250, verbose_name='USER LOGIN NAME')),
                ('password', models.CharField(max_length=250, verbose_name='USER PASSWORD')),
                ('mailid', models.CharField(max_length=250, verbose_name='USER MAIL ID')),
            ],
        ),
    ]
